export const CERTIFIED_STANDARDS = ['NP 4552','ISO 14001','ISO 50001','ISO 9001'];
export function standardMatches(value){
 const matches=String(value).toUpperCase().matchAll(/\b(ISO|NP)[\s\u00a0:–-]*(?:EN[\s-]*)?(?:ISO[\s-]*)?(?:[/\s-]*IEC[\s-]*)?(\d{4,6})(?!\d)/g);
 return [...new Set([...matches].map(m=>m[1]==='NP'&&m[2]==='4552'?'NP 4552':'ISO '+m[2]))];
}
export function isCertifiedStandardsOnly(value){const codes=standardMatches(value);return codes.length>0&&codes.every(code=>CERTIFIED_STANDARDS.includes(code));}
export const TOPICS = [
 {id:'tudo',label:'Tudo',pt:'ambiente OR sustentabilidade OR reciclagem OR biorresíduos OR "gestão da água" OR "mobilidade sustentável" OR "espaços verdes" OR urbanismo OR "engenharia hidráulica" OR "arquitetura paisagística" OR "segurança no trabalho" OR "NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',en:'"urban sustainability" OR recycling OR "water management" OR "green infrastructure" OR "sustainable mobility" OR "water engineering" OR "landscape architecture" OR "occupational safety" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"'},
 {id:'ambiente',label:'Ambiente',pt:'"proteção ambiental" OR biodiversidade OR "alterações climáticas" OR poluição',en:'"environmental protection" OR biodiversity OR "climate adaptation" OR pollution',match:'ambient|biodivers|climat|polu|pollut|ecolog|conserva|emisso|environment|ecosystem|habitat'},
 {id:'agua',label:'Água',pt:'"gestão da água" OR "abastecimento de água" OR "águas residuais" OR "eficiência hídrica" OR dessalinização',en:'"water management" OR wastewater OR "water supply" OR desalination OR "water reuse"',match:'\\bagua\\b|\\bwater\\b|hidric|hydro|dessalin|desalin|saneamento|drought|seca|wastewater|waterway|river basin|reservoir|irrigation'},
 {id:'residuos',label:'Resíduos / reciclagem',pt:'resíduos OR reciclagem OR "economia circular"',en:'"waste management" OR recycling OR "circular economy"',match:'residu|waste|recic|recycl|circular economy|plastic waste|plastic recycling|lixo|landfill|aterro|reutiliz|reuse'},
 {id:'biorresiduos',label:'Biorresíduos',pt:'biorresíduos OR compostagem OR "resíduos alimentares" OR "recolha de orgânicos"',en:'biowaste OR composting OR "food waste collection" OR "organic waste" OR "anaerobic digestion"',match:'biorres|biowaste|compost|residuos aliment|food waste|organic waste|organics collection|anaerob|biodigest|restos alimentares'},
 {id:'infraestruturas',label:'Infraestruturas',pt:'infraestruturas OR "rede de saneamento" OR "drenagem urbana" OR "rede de abastecimento" OR "obras públicas"',en:'infrastructure OR "urban drainage" OR "water infrastructure" OR "public works"',match:'infraestrutur|infrastructur|drenag|drainage|saneamento|abastecimento|sewer|pipeline|pipe network|public works|obras publicas|bridge|road network|water network|rail infrastructure'},
 {id:'espacos-verdes',label:'Espaços verdes',pt:'"espaços verdes" OR "arborização urbana" OR "parques urbanos" OR "florestas urbanas"',en:'"urban green spaces" OR "urban forests" OR "urban parks" OR "urban trees" OR "green roofs"',match:'espacos verdes|green spaces?|urban greening|urban forest|green roof|tree canopy|arboriz|parques urbanos|jardins urbanos|urban parks|public parks|parques e jardins|urban trees|nature-based solutions'},
 {id:'urbanismo',label:'Planeamento urbanístico',pt:'"planeamento urbanístico" OR "planeamento urbano" OR "reabilitação urbana" OR "urbanismo sustentável"',en:'"sustainable urban planning" OR "urban regeneration" OR "15-minute city" OR "urban design"',match:'urban planning|city planning|spatial planning|land use planning|zoning|planeamento urban|planeamento territorial|urbanismo|urban regeneration|urban design|reabilitacao urbana|15-minute cit|cidade de 15 minutos'},
 {id:'mobilidade',label:'Mobilidade',pt:'"mobilidade sustentável" OR "transportes públicos" OR ciclovias OR "mobilidade elétrica"',en:'"sustainable mobility" OR "public transport" OR "cycling infrastructure" OR "electric buses"',match:'mobilidade|mobility|public transport|public transit|sustainable transport|transportes publicos|ciclov|cycling|cycle lane|bike lane|bicycle|pedestrian|pedonal|autocarro|onibus|bus rapid transit|metro|tram|light rail|rail service|car-free'},
 {id:'sustentabilidade',label:'Sustentabilidade',pt:'sustentabilidade OR descarbonização OR "transição energética" OR "economia circular"',en:'sustainability OR decarbonisation OR "energy transition" OR "circular economy"',match:'sustent|sustainab|descarbon|decarbon|transicao energetica|energy transition|circular economy|emisso|emission|renewable energy|energia renovavel|energy efficiency|eficiencia energetica|net zero|climate neutral|desenvolvimento sustentavel'},
 {id:'ciencia',label:'Ciência',pt:'("estudo" OR "investigação") (ambiente OR água OR resíduos OR biodiversidade)',en:'"environmental research" OR "climate research" OR "water research" OR "recycling research"',match:'environmental research|climate research|water research|waste research|biodiversity study|environmental science|climate study|estudo ambiental|investigacao ambiental|investigacao sobre agua|ciencia ambiental|scientific study'},
 {id:'tecnologia',label:'Tecnologia',pt:'("inovação" OR "tecnologia") (ambiente OR água OR resíduos OR sustentabilidade)',en:'"water technology" OR "recycling technology" OR "environmental technology" OR "sustainability innovation"',match:'environmental technology|green technology|water technology|recycling technology|waste technology|smart water|smart irrigation|tecnologia ambiental|tecnologia da agua|tecnologia de reciclagem|inovacao ambiental|monitorizacao ambiental|environmental monitoring'},
 {id:'engenharia',label:'Engenharia',pt:'"engenharia hidráulica" OR "engenharia sanitária" OR "engenharia de infraestruturas" OR "engenharia da água" OR "tratamento de águas"',en:'"water engineering" OR "hydraulic engineering" OR "wastewater engineering" OR "civil infrastructure engineering"',match:'engenhari|engineering|hidraulic|hydraulic|saneamento|water treatment|tratamento.{0,20}agua|infraestrutur|infrastruct',sector:'agua|water|infraestrutur|infrastruct|hidraul|hydraul|sanita|saneamento|sewer|drenag|drain|barrag|dam|tubag|pipe'},
 {id:'arquitetura-paisagistica',label:'Arquitetura Paisagística',pt:'"arquitetura paisagística" OR "arquitectura paisagista" OR "arquitetura paisagista" OR "projeto paisagístico" OR "desenho da paisagem"',en:'"landscape architecture" OR "landscape design" OR "landscape planning"',match:'arquitetura paisag|arquitectura paisag|landscape architecture|landscape design|landscape planning|projeto paisag|projeto de paisagismo|desenho da paisagem'},
 {id:'seguranca-trabalho',label:'Higiene e Segurança no Trabalho',pt:'"segurança no trabalho" OR "higiene ocupacional" OR "segurança e saúde no trabalho" OR "prevenção de riscos profissionais"',en:'"occupational safety" OR "occupational hygiene" OR "workplace safety" OR "worker safety"',match:'seguranca no trabalho|saude e seguranca no trabalho|higiene ocupacional|riscos profissionais|occupational safety|occupational health|workplace safety|health and safety at work|industrial hygiene'},
 {id:'normas',label:'Normas',pt:'"NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',en:'"NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',match:'(?:np|iso)[ -]*(?:4552|14001|50001|9001)',strict:true},
 {id:'cultura' ,label:'Cultura',pt:'("arte" OR "educação" OR "festival") (ambiente OR sustentabilidade OR reciclagem)',en:'"environmental art" OR "environmental education" OR "sustainability festival" OR "climate art"',match:'environmental art|climate art|eco art|arte ambiental|arte e sustentabilidade|environmental education|educacao ambiental|festival sustentavel|sustainability festival|cultura ambiental'}
];
export function feedDefinitions(topic){
 const pt=`(${topic.pt}) (Portugal OR site:.pt) when:30d`;
 const en=`(${topic.en}) when:30d`;
 function google(query,lang){const params=new URLSearchParams({q:query,hl:lang==='pt'?'pt-PT':'en-GB',gl:lang==='pt'?'PT':'GB',ceid:lang==='pt'?'PT:pt-150':'GB:en'});return 'https://news.google.com/rss/search?'+params;}
 return [
  {id:'google-pt',name:'Google Notícias · Portugal',url:google(pt,'pt'),lang:'pt',kind:'aggregator'},
  {id:'google-en',name:'Google News · English',url:google(en,'en'),lang:'en',kind:'aggregator'},
  ...[
   {id:'ersar',name:'ERSAR · Notícias',domain:'ersar.pt',sourceURL:'https://www.ersar.pt/pt_comunicacao_noticias.html'},
   {id:'apa',name:'APA · Notícias',domain:'apambiente.pt',sourceURL:'https://apambiente.pt/'},
   {id:'adp',name:'Águas de Portugal · Notícias',domain:'adp.pt',sourceURL:'https://www.adp.pt/'},
   {id:'apda',name:'APDA · Notícias',domain:'apda.pt',sourceURL:'https://www.apda.pt/'}
  ].map(source=>({id:`${source.id}-news`,name:source.name,url:google(`(${topic.pt}) site:${source.domain} when:30d`,'pt'),sourceURL:source.sourceURL,lang:'pt',kind:'aggregator',site:source.domain})),
  {id:'ambiente-magazine',name:'Ambiente Magazine',url:'https://www.ambientemagazine.com/feed/',lang:'pt',kind:'direct'},
  {id:'guardian',name:'The Guardian · Environment',url:'https://www.theguardian.com/environment/rss',lang:'en',kind:'direct'}
 ];
}
