export const CERTIFIED_STANDARDS = ['NP 4552','ISO 14001','ISO 50001','ISO 9001'];
export function standardMatches(value){
 const matches=String(value).toUpperCase().matchAll(/\b(ISO|NP)[\s\u00a0:–-]*(?:EN[\s-]*)?(?:ISO[\s-]*)?(?:[/\s-]*IEC[\s-]*)?(\d{4,6})(?!\d)/g);
 return [...new Set([...matches].map(m=>m[1]==='NP'&&m[2]==='4552'?'NP 4552':'ISO '+m[2]))];
}
export function isCertifiedStandardsOnly(value){const codes=standardMatches(value);return codes.length>0&&codes.every(code=>CERTIFIED_STANDARDS.includes(code));}
export const TOPICS = [
 {id:'tudo',label:'Tudo',pt:'ambiente OR sustentabilidade OR reciclagem OR biorresíduos OR "gestão da água" OR "mobilidade sustentável" OR "espaços verdes" OR urbanismo OR "engenharia hidráulica" OR "arquitetura paisagística" OR "segurança no trabalho" OR "NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',en:'"urban sustainability" OR recycling OR "water management" OR "green infrastructure" OR "sustainable mobility" OR "water engineering" OR "landscape architecture" OR "occupational safety" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"'},
 {id:'ambiente',label:'Ambiente',pt:'"proteção ambiental" OR biodiversidade OR "alterações climáticas" OR poluição',en:'"environmental protection" OR biodiversity OR "climate adaptation" OR pollution',match:'ambient|biodivers|climat|polui|pollut|ecolog|conserva'},
 {id:'agua',label:'Água',pt:'"gestão da água" OR "abastecimento de água" OR "águas residuais" OR "eficiência hídrica" OR dessalinização',en:'"water management" OR wastewater OR "water supply" OR desalination OR "water reuse"',match:'agua|water|hidric|hydro|dessalin|desalin|saneamento|drought|seca'},
 {id:'residuos',label:'Resíduos / reciclagem',pt:'resíduos OR reciclagem OR "economia circular"',en:'"waste management" OR recycling OR "circular economy"',match:'resid|waste|recic|recycl|circular|plastic|lixo'},
 {id:'biorresiduos',label:'Biorresíduos',pt:'biorresíduos OR compostagem OR "resíduos alimentares" OR "recolha de orgânicos"',en:'biowaste OR composting OR "food waste collection" OR "organic waste" OR "anaerobic digestion"',match:'biorres|biowaste|compost|alimentar|food waste|organic|organico|anaerob|biodigest'},
 {id:'infraestruturas',label:'Infraestruturas',pt:'"infraestruturas verdes" OR "infraestruturas urbanas" OR "rede de saneamento" OR "drenagem urbana" OR "rede de abastecimento"',en:'"green infrastructure" OR "resilient infrastructure" OR "urban drainage" OR "water infrastructure"',match:'infraestrutur|infrastruct|drenag|drainage|saneamento|abastecimento|sewer|rede|network'},
 {id:'espacos-verdes',label:'Espaços verdes',pt:'"espaços verdes" OR "arborização urbana" OR "parques urbanos" OR "florestas urbanas"',en:'"urban green spaces" OR "urban forests" OR "urban parks" OR "urban trees" OR "green roofs"',match:'espacos verdes|green space|arbor|tree|parque|park|forest|florest|jardim|garden|green roof|nature'},
 {id:'urbanismo',label:'Planeamento urbanístico',pt:'"planeamento urbanístico" OR "planeamento urbano" OR "reabilitação urbana" OR "urbanismo sustentável"',en:'"sustainable urban planning" OR "urban regeneration" OR "15-minute city" OR "urban design"',match:'urban|planeamento|planning|regener|reabilita|cidade|cities|city'},
 {id:'mobilidade',label:'Mobilidade',pt:'"mobilidade sustentável" OR "transportes públicos" OR ciclovias OR "mobilidade elétrica"',en:'"sustainable mobility" OR "public transport" OR "cycling infrastructure" OR "electric buses"',match:'mobil|transport|ciclov|cycl|autocar|bus|pedon|pedestrian|transit|metro|rail'},
 {id:'sustentabilidade',label:'Sustentabilidade',pt:'sustentabilidade OR descarbonização OR "transição energética" OR "economia circular"',en:'sustainability OR decarbonisation OR "energy transition" OR "circular economy"',match:'sustent|sustainab|descarbon|decarbon|energia|energy|circular|emisso|emission'},
 {id:'ciencia',label:'Ciência',pt:'("estudo" OR "investigação") (ambiente OR água OR resíduos OR biodiversidade)',en:'"environmental research" OR "climate research" OR "water research" OR "recycling research"',match:'estudo|investiga|ciencia|science|research|study|scientist'},
 {id:'tecnologia',label:'Tecnologia',pt:'("inovação" OR "tecnologia") (ambiente OR água OR resíduos OR sustentabilidade)',en:'"water technology" OR "recycling technology" OR "environmental technology" OR "sustainability innovation"',match:'tecnolog|technolog|inova|innova|sensor|digital|intelig|smart'},
 {id:'engenharia',label:'Engenharia',pt:'"engenharia hidráulica" OR "engenharia sanitária" OR "engenharia de infraestruturas" OR "engenharia da água"',en:'"water engineering" OR "hydraulic engineering" OR "wastewater engineering" OR "civil infrastructure engineering"',practicePT:['adp.pt','lnec.pt','ordemengenheiros.pt','ambientemagazine.com'],practiceEN:['iwa-network.org','waterworld.com','wateronline.com','asce.org'],match:'engenhari|engineering|hidraulic|hydraulic|saneamento|water treatment|tratamento.*agua|infraestrutur|infrastruct',sector:'agua|water|infraestrutur|infrastruct|hidraul|hydraul|sanita|saneamento|sewer|drenag|drain|barrag|dam|tubag|pipe',strict:true},
 {id:'arquitetura-paisagistica',label:'Arquitetura Paisagística',pt:'"arquitetura paisagística" OR "arquitectura paisagista" OR "arquitetura paisagista" OR "projeto paisagístico"',en:'"landscape architecture" OR "landscape architect" OR "landscape design"',match:'paisagi|paisagis|paisajis|landscape architect|landscape design',strict:true,practicePT:['apap.pt','smart-cities.pt','arquitecturas.pt','ambientemagazine.com'],practiceEN:['landezine.com','worldlandscapearchitect.com','asla.org','landscapeinstitute.org']},
 {id:'seguranca-trabalho',label:'Higiene e Segurança no Trabalho',pt:'"segurança no trabalho" OR "higiene ocupacional" OR "segurança e saúde no trabalho" OR "prevenção de riscos profissionais"',en:'"occupational safety" OR "occupational hygiene" OR "workplace safety" OR "worker safety"',match:'seguranca.*trabalho|saude.*trabalho|higiene.*trabalho|ocupacional|riscos profissionais|occupational|workplace safety|worker safety|work.related',strict:true,practicePT:['act.gov.pt','osha.europa.eu','dgs.pt'],practiceEN:['osha.europa.eu','hse.gov.uk','osha.gov','ilo.org'],practiceTermsPT:'(prevenção OR guia OR projeto OR boas práticas)',practiceTermsEN:'(prevention OR guidance OR project OR good practice)'},
 {id:'normas',label:'Normas',pt:'"NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',en:'"NP 4552" OR "ISO 14001" OR "ISO 50001" OR "ISO 9001"',match:'(?:np|iso)[ -]*(?:4552|14001|50001|9001)',strict:true,practicePT:['ipq.pt','apcergroup.com','sgs.com','adp.pt'],practiceEN:['iso.org','bsigroup.com','sgs.com'],practiceTermsPT:'(certificação OR implementação OR auditoria OR conciliação)',practiceTermsEN:'(certification OR implementation OR audit OR project)'},
 {id:'cultura' ,label:'Cultura',pt:'("arte" OR "educação" OR "festival") (ambiente OR sustentabilidade OR reciclagem)',en:'"environmental art" OR "environmental education" OR "sustainability festival" OR "climate art"',match:'cultur|arte|\\bart\\b|educa|festival|sensibiliza'}
];
export const PRACTICE_PT = ['ambientemagazine.com','greensavers.sapo.pt','smart-cities.pt','apambiente.pt','adp.pt','ersar.pt'];
export const PRACTICE_EN = ['c40.org','c40knowledgehub.org','wri.org','eea.europa.eu','smartcitiesdive.com','wastedive.com','circularonline.co.uk','edie.net','iclei.org'];
const sites = list=>'('+list.map(d=>'site:'+d).join(' OR ')+')';
export function feedDefinitions(topic,mode){
 const practice=mode==='praticas';
 const pt=`(${topic.pt}) ${practice?sites(topic.practicePT||PRACTICE_PT)+' '+(topic.practiceTermsPT||'(projeto OR iniciativa OR solução OR inovação OR piloto OR exemplo)')+' when:365d':'(Portugal OR site:.pt) when:30d'}`;
 const en=`(${topic.en}) ${practice?sites(topic.practiceEN||PRACTICE_EN)+' '+(topic.practiceTermsEN||'(project OR initiative OR solution OR pilot OR "case study" OR innovation)')+' when:365d':'when:30d'}`;
 function google(query,lang){const params=new URLSearchParams({q:query,hl:lang==='pt'?'pt-PT':'en-GB',gl:lang==='pt'?'PT':'GB',ceid:lang==='pt'?'PT:pt-150':'GB:en'});return 'https://news.google.com/rss/search?'+params;}
 return [
  {id:'google-pt',name:'Google Notícias · Portugal',url:google(pt,'pt'),lang:'pt',kind:'aggregator',practice},
  {id:'google-en',name:'Google Notícias · Internacional',url:google(en,'en'),lang:'en',kind:'aggregator',practice},
  {id:'ambiente-magazine',name:'Ambiente Magazine',url:'https://www.ambientemagazine.com/feed/',lang:'pt',kind:'direct',practice:false},
  {id:'guardian',name:'The Guardian · Environment',url:'https://www.theguardian.com/environment/rss',lang:'en',kind:'direct',practice:false}
 ];
}
